#!/usr/bin/env python3
"""Generate .codex/agents/*.toml from .claude/agents/*.md.

The two agent formats describe the same roles. Maintaining them by hand means
they drift, and a drifted role definition is worse than none: a contributor
using Codex silently gets different rules than one using Claude Code. So the
Markdown files are the source and the TOML is generated.

Run with --check in CI to fail on drift instead of rewriting.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / ".claude" / "agents"
DST = ROOT / ".codex" / "agents"

HEADER = (
    "# GENERATED by tools/sync_agents.py from ../../.claude/agents/{name}.md\n"
    "# Edit the Markdown source, then re-run the tool. Do not edit this file.\n\n"
)


def parse(md: str) -> tuple[dict[str, str], str]:
    """Split YAML-ish frontmatter from the body. The frontmatter here is a flat
    key: value map, so a real YAML parser would be a dependency for nothing."""
    if not md.startswith("---\n"):
        raise ValueError("missing frontmatter")
    _, fm, body = md.split("---\n", 2)
    meta: dict[str, str] = {}
    for line in fm.splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    return meta, body.strip()


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(name: str, meta: dict[str, str], body: str) -> str:
    out = HEADER.format(name=name)
    out += f'name = "{toml_escape(meta.get("name", name))}"\n'
    out += f'description = "{toml_escape(meta.get("description", ""))}"\n'
    if "model" in meta:
        out += f'model = "{toml_escape(meta["model"])}"\n'
    if "tools" in meta:
        tools = [t.strip() for t in meta["tools"].split(",") if t.strip()]
        out += "tools = [" + ", ".join(f'"{t}"' for t in tools) + "]\n"
    # A multi-line basic string would need every internal quote escaped; the
    # literal form ''' ... ''' passes the prose through untouched.
    out += f"developer_instructions = '''\n{body}\n'''\n"
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail on drift, do not write")
    args = ap.parse_args()

    DST.mkdir(parents=True, exist_ok=True)
    drift: list[str] = []
    for md_path in sorted(SRC.glob("*.md")):
        name = md_path.stem
        meta, body = parse(md_path.read_text(encoding="utf-8"))
        if "'''" in body:
            raise ValueError(f"{md_path}: body contains ''' and cannot be embedded")
        rendered = render(name, meta, body)
        out_path = DST / f"{name}.toml"
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else None
        if current == rendered:
            continue
        if args.check:
            drift.append(name)
        else:
            out_path.write_text(rendered, encoding="utf-8")
            print(f"wrote {out_path.relative_to(ROOT)}")

    stale = {p.stem for p in DST.glob("*.toml")} - {p.stem for p in SRC.glob("*.md")}
    for name in sorted(stale):
        if args.check:
            drift.append(f"{name} (stale)")
        else:
            (DST / f"{name}.toml").unlink()
            print(f"removed stale {name}.toml")

    if drift:
        print("agent definitions out of sync: " + ", ".join(drift), file=sys.stderr)
        print("run: python3 tools/sync_agents.py", file=sys.stderr)
        return 1
    if args.check:
        print(f"agent definitions in sync ({len(list(SRC.glob('*.md')))} roles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
